name: APK and AAB Build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.24
  APK_PATH: "build/apk/app-release.apk"
  AAB_PATH: "build/aab/app-release.aab"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: my_flutter_project # Adjust if your Flutter project is in a subdirectory

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: my_flutter_project # Adjust this if needed

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Clean up previous build artifacts if pubspec.yaml exists
      run: |
        if [ -f pubspec.yaml ]; then
          rm -rf build
          flutter clean
        else
          echo "Skipping clean-up as pubspec.yaml was not found."
        fi
      working-directory: my_flutter_project # Adjust this if needed

    - name: Build APK and AAB if pubspec.yaml exists
      run: |
        if [ -f pubspec.yaml ]; then
          flet build apk --build-version ${{ env.BUILD_VERSION }} --build-number ${{ env.BUILD_NUMBER }} --verbose
          flet build aab --build-version ${{ env.BUILD_VERSION }} --build-number ${{ env.BUILD_NUMBER }} --verbose
        else
          echo "Skipping build as pubspec.yaml was not found."
        fi
      working-directory: my_flutter_project # Adjust this if needed

    - name: Check for Build Directory
      run: |
        if [ -d "build" ]; then
          echo "Build directory exists. Proceeding to list files."
        else
          echo "Build directory does not exist. Skipping file listing."
          exit 0
        fi
      working-directory: my_flutter_project # Adjust this if needed

    - name: List All Files in Build Directory
      if: always()
      run: |
        find build -type f -print

    - name: Verify APK and AAB Existence
      id: verify-files
      run: |
        if [ -f "$APK_PATH" ]; then
          echo "APK file found at $APK_PATH"
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
        else
          echo "Error: APK file not found at $APK_PATH!"
          exit 1
        fi
        if [ -f "$AAB_PATH" ]; then
          echo "AAB file found at $AAB_PATH"
          echo "AAB_PATH=$AAB_PATH" >> $GITHUB_ENV
        else
          echo "Error: AAB file not found at $AAB_PATH!"
          exit 1
        fi
      working-directory: my_flutter_project # Adjust this if needed

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk-build-artifact
        path: ${{ env.APK_PATH }}
        if-no-files-found: error
        overwrite: false

    - name: Upload AAB Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: aab-build-artifact
        path: ${{ env.AAB_PATH }}
        if-no-files-found: error
        overwrite: false
